pipeline {
    agent any
    tools {
        maven '3.9.9'  // Specify the exact name you set for Maven in Jenkins
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('last deliver') {
            steps {
                echo 'last delivered'
            }
        }
    }
}
